"use client";
import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowRight, GitMerge, ClipboardCheck, Tag, Sparkles } from "lucide-react";

const HIGHLIGHTS = [
  {
    icon: Tag,
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/20",
    title: "@req Annotations",
    detail: "Every public function generated by code-generator now carries a @req tag linking it directly to the requirement it satisfies.",
  },
  {
    icon: ClipboardCheck,
    color: "text-violet-400",
    bg: "bg-violet-500/10",
    border: "border-violet-500/20",
    title: "Definition of Done",
    detail: "Tasks now carry explicit acceptance criteria and DoD items. Before release, each DoD item is verified against code, tests, and the database schema.",
  },
  {
    icon: GitMerge,
    color: "text-green-400",
    bg: "bg-green-500/10",
    border: "border-green-500/20",
    title: "3-Tier Traceability",
    detail: "Requirements link forward to tasks (req_task_map), tasks link to code via @req annotations, and naming conventions serve as fallback — every gap is flagged.",
  },
  {
    icon: Sparkles,
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/20",
    title: "Prompt Normalizer",
    detail: "Step 0 in every pipeline: vague inputs are structured before routing. Confident intents route immediately; ambiguous ones get one targeted clarification question.",
  },
];

export function WhatsNewBanner() {
  return (
    <section className="mx-auto max-w-7xl px-6 py-10">
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        className="rounded-2xl border border-violet-500/20 bg-gradient-to-br from-violet-50 dark:from-violet-950/40 via-zinc-50 dark:via-zinc-900 to-zinc-50 dark:to-zinc-900 p-8"
      >
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-violet-500/30 bg-violet-500/10 px-3 py-1 text-xs text-violet-400 font-medium mb-3">
              <span className="h-1.5 w-1.5 rounded-full bg-violet-400 animate-pulse" />
              New in v2.5.0 — EETF Adoption
            </div>
            <h2 className="text-2xl font-bold text-zinc-900 dark:text-white">
              Full Requirements Traceability
            </h2>
            <p className="text-zinc-600 dark:text-zinc-400 text-sm mt-1 max-w-lg">
              Every requirement is now traceable from analysis through to code, tests, and documentation — automatically.
            </p>
          </div>
          <Link
            href="/changelog"
            className="shrink-0 inline-flex items-center gap-2 rounded-lg border border-zinc-300 dark:border-zinc-700 hover:border-zinc-400 dark:hover:border-zinc-500 px-4 py-2 text-sm text-zinc-600 dark:text-zinc-300 hover:text-zinc-900 dark:hover:text-white transition-colors"
          >
            Full Changelog
            <ArrowRight size={14} />
          </Link>
        </div>

        {/* Highlight cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {HIGHLIGHTS.map((h) => (
            <motion.div
              key={h.title}
              initial={{ opacity: 0, y: 8 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className={`rounded-xl border ${h.border} ${h.bg} p-4`}
            >
              <div className="flex items-center gap-2 mb-2">
                <h.icon size={16} className={h.color} />
                <span className={`text-sm font-semibold ${h.color}`}>{h.title}</span>
              </div>
              <p className="text-xs text-zinc-600 dark:text-zinc-400 leading-relaxed">{h.detail}</p>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </section>
  );
}
